### PR TITLE
Fix iOS Property not found on object of type 'AppDelegate *'

### PR DESCRIPTION
**Pull request by STtraveller**

### CODE REVIEW

**Comment by tomavic** [comment]
Thanks for your interest in our plugin. I'll review this and then merge it.

**Comment by FlorinSerban** [comment]
Hi,
Can you please create a new release with the latest changes?
When I install the plugin is not having having the changes made by @STtraveller

**Comment by STtraveller** [comment]
> Hi,
> 
> Can you please create a new release with the latest changes?
> 
> When I install the plugin is not having having the changes made by @STtraveller

I guess the plugin author haven’t update the release to npm 

You can use this command to get the latest version from github

```
cordova plugin add https://github.com/tomavic/cordova-apple-wallet.git
```

**Comment by tomavic** [comment]
@STtraveller  @FlorinSerban 
Hi guys, I have been so busy the last month. I am going to update the release on npm. Also I will add any missing guides to README file.

Thanks for your interest in the plugin.

**Pull request merged**
